import type { Property, Agent, Testimonial } from './types';

const agents: Agent[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    title: 'Senior Real Estate Agent',
    phone: '123-456-7890',
    email: 'alice.j@realestate.com',
    image: 'https://placehold.co/400x400.png',
    propertiesCount: 5,
    data_ai_hint: "professional woman"
  },
  {
    id: '2',
    name: 'Bob Williams',
    title: 'Commercial Property Specialist',
    phone: '123-456-7891',
    email: 'bob.w@realestate.com',
    image: 'https://placehold.co/400x400.png',
    propertiesCount: 3,
    data_ai_hint: "professional man"
  },
   {
    id: '3',
    name: 'Charlie Brown',
    title: 'Luxury Home Consultant',
    phone: '123-456-7892',
    email: 'charlie.b@realestate.com',
    image: 'https://placehold.co/400x400.png',
    propertiesCount: 4,
    data_ai_hint: "friendly man"
  },
];

const properties: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Loft',
    price: 1200000,
    address: '123 Main St, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Apartment',
    description: 'A beautiful and spacious loft in the heart of the city. Features high ceilings, large windows, and a modern kitchen. Perfect for urban living.',
    amenities: ['Gym', 'Pool', 'Rooftop Deck', '24/7 Security'],
    agentId: '1',
    data_ai_hint: "modern apartment interior"
  },
  {
    id: '2',
    title: 'Suburban Family Home',
    price: 750000,
    address: '456 Oak Ave, Suburbia, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A charming family home in a quiet suburban neighborhood. Features a large backyard, a two-car garage, and a newly renovated kitchen.',
    amenities: ['Backyard', 'Garage', 'Fireplace', 'Modern Kitchen'],
    agentId: '2',
    data_ai_hint: "suburban house exterior"
  },
  {
    id: '3',
    title: 'Luxury Beachfront Villa',
    price: 3500000,
    address: '789 Ocean Blvd, Beachtown, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 5000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Villa',
    description: 'An exquisite beachfront villa with breathtaking ocean views. Features a private pool, direct beach access, and a home theater.',
    amenities: ['Private Pool', 'Beach Access', 'Home Theater', 'Gourmet Kitchen', 'Ocean View'],
    agentId: '3',
    data_ai_hint: "luxury villa beach"
  },
  {
    id: '4',
    title: 'Cozy Condo with City View',
    price: 550000,
    address: '101 Pine St, Anytown, USA',
    bedrooms: 1,
    bathrooms: 1,
    area: 800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Condo',
    description: 'A cozy and modern condo with a stunning view of the city skyline. Perfect for a young professional or couple. Building includes a gym and pool.',
    amenities: ['Gym', 'Pool', 'Concierge', 'City View'],
    agentId: '1',
    data_ai_hint: "modern condo interior"
  },
  {
    id: '5',
    title: 'Spacious House with Garden',
    price: 850000,
    address: '222 Maple Dr, Suburbia, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 2200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A spacious house with a beautiful garden and outdoor patio. Ideal for families who love the outdoors. Includes a large living room and a formal dining area.',
    amenities: ['Garden', 'Patio', 'Garage', 'Hardwood Floors'],
    agentId: '2',
    data_ai_hint: "house garden"
  },
  {
    id: '6',
    title: 'Penthouse with Rooftop Terrace',
    price: 2500000,
    address: '333 Sky High Rd, Anytown, USA',
    bedrooms: 3,
    bathrooms: 4,
    area: 3000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Apartment',
    description: 'A stunning penthouse apartment with a private rooftop terrace offering 360-degree city views. Luxury finishes throughout.',
    amenities: ['Rooftop Terrace', 'Private Elevator', 'Concierge', ' panoramic views'],
    agentId: '3',
    data_ai_hint: "luxury penthouse interior"
  },
  {
    id: '7',
    title: 'Quaint Cottage in the Woods',
    price: 450000,
    address: '77 Forest Lane, Woodland, USA',
    bedrooms: 2,
    bathrooms: 1,
    area: 1200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A cozy cottage surrounded by nature. Perfect for a peaceful retreat. Features a stone fireplace and a large wooden deck.',
    amenities: ['Fireplace', 'Deck', 'Hiking Trails Access'],
    agentId: '1',
    data_ai_hint: 'cottage woods'
  },
  {
    id: '8',
    title: 'Sleek Urban Studio',
    price: 480000,
    address: '88 City Center, Metropolis, USA',
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Apartment',
    description: 'A stylish and efficient studio in a bustling urban center. Close to public transport and nightlife.',
    amenities: ['Modern Appliances', 'Walk-in Closet', 'Building Security'],
    agentId: '2',
    data_ai_hint: 'urban studio'
  },
  {
    id: '9',
    title: 'Historic Townhouse',
    price: 980000,
    address: '99 Old Town Rd, Historyville, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A beautifully preserved townhouse with historic charm and modern updates. Features original hardwood floors and a private garden.',
    amenities: ['Private Garden', 'Historic Details', 'Renovated Kitchen'],
    agentId: '3',
    data_ai_hint: 'historic townhouse'
  },
  {
    id: '10',
    title: 'Mountain View Condo',
    price: 620000,
    address: '10 Mountain Pass, Summit, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Condo',
    description: 'A comfortable condo with stunning mountain views from every window. Includes access to a community lodge and ski slopes.',
    amenities: ['Mountain View', 'Ski-in/Ski-out', 'Community Hot Tub'],
    agentId: '1',
    data_ai_hint: 'mountain condo'
  },
  {
    id: '11',
    title: 'Riverside Family Retreat',
    price: 1100000,
    address: '111 Riverbend Dr, Riverton, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A large family home on the river. Features a private dock, spacious lawn, and a game room.',
    amenities: ['River Access', 'Private Dock', 'Game Room'],
    agentId: '2',
    data_ai_hint: 'house river'
  },
  {
    id: '12',
    title: 'Eco-Friendly Modern Home',
    price: 1350000,
    address: '12 Solar Way, Greenville, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A state-of-the-art eco-friendly home with solar panels and sustainable materials. Designed for green living without sacrificing luxury.',
    amenities: ['Solar Panels', 'Rainwater Harvesting', 'Smart Home System'],
    agentId: '3',
    data_ai_hint: 'eco friendly house'
  },
  {
    id: '13',
    title: 'Artist Loft with Studio Space',
    price: 890000,
    address: '13 Creative Circle, Artstown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 2000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A spacious loft with high ceilings and a dedicated studio space, perfect for artists and creatives.',
    amenities: ['Studio Space', 'High Ceilings', 'Natural Light'],
    agentId: '1',
    data_ai_hint: 'artist loft'
  },
  {
    id: '14',
    title: 'Downtown High-Rise Apartment',
    price: 1500000,
    address: '1400 Skyline Ave, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Apartment',
    description: 'A luxury apartment on a high floor with panoramic city views. Building has a pool, gym, and 24/7 concierge.',
    amenities: ['Panoramic Views', 'Floor-to-Ceiling Windows', 'Valet Parking'],
    agentId: '2',
    data_ai_hint: 'luxury apartment'
  },
  {
    id: '15',
    title: 'Ranch-Style Country House',
    price: 950000,
    address: '15 Prairie Lane, Countryside, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 3500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A sprawling ranch-style house on a large plot of land. Features horse stables and wide-open spaces.',
    amenities: ['Large Acreage', 'Horse Stables', 'Wraparound Porch'],
    agentId: '3',
    data_ai_hint: 'ranch house'
  },
  {
    id: '16',
    title: 'Lakeside Cabin',
    price: 680000,
    address: '16 Water\'s Edge, Laketown, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A charming cabin with direct lake access. Perfect for fishing, boating, and summer getaways.',
    amenities: ['Lakefront', 'Private Dock', 'Screened Porch'],
    agentId: '1',
    data_ai_hint: 'lake cabin'
  },
  {
    id: '17',
    title: 'Chic Urban Condo',
    price: 720000,
    address: '17 Trendsetter Way, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Condo',
    description: 'A very stylish condo in a trendy neighborhood, known for its boutiques and cafes. Features a balcony and designer finishes.',
    amenities: ['Balcony', 'Designer Finishes', 'Community Lounge'],
    agentId: '2',
    data_ai_hint: 'urban condo'
  },
  {
    id: '18',
    title: 'Mediterranean-Style Villa',
    price: 2800000,
    address: '18 Vineyard Valley, Wine Country, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Villa',
    description: 'An elegant Mediterranean-style villa with a courtyard, fountain, and wine cellar. Set in a beautiful vineyard.',
    amenities: ['Courtyard', 'Wine Cellar', 'Swimming Pool'],
    agentId: '3',
    data_ai_hint: 'mediterranean villa'
  },
  {
    id: '19',
    title: 'Affordable Starter Home',
    price: 350000,
    address: '19 Opportunity Ave, Suburbia, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A perfect and affordable starter home for a new family. Features a fenced-in backyard and is close to schools.',
    amenities: ['Fenced Yard', 'Near Schools', 'Updated Appliances'],
    agentId: '1',
    data_ai_hint: 'starter home'
  },
  {
    id: '20',
    title: 'Industrial Loft Conversion',
    price: 1150000,
    address: '20 Factory Row, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 2400,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A unique loft in a converted factory. Features exposed brick, high ceilings, and industrial details.',
    amenities: ['Exposed Brick', 'High Ceilings', 'Freight Elevator Access'],
    agentId: '2',
    data_ai_hint: 'industrial loft'
  },
  {
    id: '21',
    title: 'Secluded Forest House',
    price: 880000,
    address: '21 Whisperwind Path, Forest, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 3000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A private and secluded home surrounded by dense forest. Perfect for nature lovers seeking tranquility.',
    amenities: ['Secluded', 'Forest Views', 'Hiking Trails'],
    agentId: '3',
    data_ai_hint: 'forest house'
  },
  {
    id: '22',
    title: 'Golf Course Estate',
    price: 4200000,
    address: '22 Fairway Drive, Greenside, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 7000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'An expansive estate on a prestigious golf course. Features a home gym, theater, and custom pool.',
    amenities: ['Golf Course View', 'Home Gym', 'Theater Room', 'Custom Pool'],
    agentId: '1',
    data_ai_hint: 'luxury house'
  },
  {
    id: '23',
    title: 'Bright and Airy Beach House',
    price: 1750000,
    address: '23 Sandy Lane, Beachtown, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A beautiful beach house with an open floor plan and plenty of natural light. Just steps from the sand.',
    amenities: ['Beach Access', 'Ocean View', 'Outdoor Shower'],
    agentId: '2',
    data_ai_hint: 'beach house'
  },
  {
    id: '24',
    title: 'Penthouse with Private Pool',
    price: 5500000,
    address: '24 Skyline Terrace, Metropolis, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 4800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Apartment',
    description: 'The ultimate in luxury living. This penthouse features a private rooftop pool and unparalleled city views.',
    amenities: ['Private Pool', 'Rooftop Terrace', '360-degree Views', 'Private Chef Kitchen'],
    agentId: '3',
    data_ai_hint: 'luxury penthouse'
  },
  {
    id: '25',
    title: 'Suburban Tudor Home',
    price: 920000,
    address: '25 Tudor Grove, Suburbia, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2700,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'Classic Tudor style home with beautiful architectural details in a family-friendly neighborhood.',
    amenities: ['Landscaped Garden', 'Two-car garage', 'Classic Architecture'],
    agentId: '1',
    data_ai_hint: 'tudor house'
  },
  {
    id: '26',
    title: 'Minimalist City Apartment',
    price: 680000,
    address: '26 Simple Street, Anytown, USA',
    bedrooms: 2,
    bathrooms: 1,
    area: 1100,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A minimalist apartment with clean lines and a focus on simplicity and function. Located in a quiet, yet central area.',
    amenities: ['Minimalist Design', 'Smart Storage', 'Quiet Street'],
    agentId: '2',
    data_ai_hint: 'minimalist apartment'
  },
  {
    id: '27',
    title: 'Desert Modern Home',
    price: 1950000,
    address: '27 Cactus Trail, Desert Springs, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 3200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A stunning modern home in the desert, designed to blend with the landscape. Features a negative-edge pool and amazing sunset views.',
    amenities: ['Desert Landscape', 'Infinity Pool', 'Sunset Views'],
    agentId: '3',
    data_ai_hint: 'desert house'
  },
  {
    id: '28',
    title: 'Garden Apartment',
    price: 650000,
    address: '28 Blossom Court, Greenville, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A lovely ground-floor apartment with a private garden patio. Perfect for those who want outdoor space in the city.',
    amenities: ['Private Garden', 'Ground Floor', 'Pet Friendly'],
    agentId: '1',
    data_ai_hint: 'garden apartment'
  },
  {
    id: '29',
    title: 'Victorian Mansion',
    price: 3200000,
    address: '29 Heritage Hill, Historyville, USA',
    bedrooms: 7,
    bathrooms: 8,
    area: 8000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A grand Victorian mansion, fully restored with meticulous attention to detail. Features a ballroom and servants quarters.',
    amenities: ['Historic Restoration', 'Ballroom', 'Large Estate'],
    agentId: '2',
    data_ai_hint: 'victorian mansion'
  },
  {
    id: '30',
    title: 'Modern Farmhouse',
    price: 1450000,
    address: '30 Country Road, Farmland, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 4000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A new-build modern farmhouse with a classic look and all the modern amenities. Features a gourmet kitchen and a large front porch.',
    amenities: ['Modern Farmhouse Style', 'Gourmet Kitchen', 'Wraparound Porch'],
    agentId: '3',
    data_ai_hint: 'modern farmhouse'
  },
  {
    id: '31',
    title: 'Sky-High City Condo',
    price: 1800000,
    address: '31 Cloud Nine, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Condo',
    description: 'Live in the clouds in this stunning high-rise condo. Features incredible views and five-star building amenities.',
    amenities: ['High Floor', 'City Views', 'Rooftop Pool'],
    agentId: '1',
    data_ai_hint: 'city condo'
  },
  {
    id: '32',
    title: 'Craftsman Bungalow',
    price: 780000,
    address: '32 Arts & Crafts Way, Suburbia, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A charming Craftsman bungalow with a cozy fireplace and built-in cabinetry. A true gem in a quiet neighborhood.',
    amenities: ['Craftsman Style', 'Cozy Fireplace', 'Built-in Shelving'],
    agentId: '2',
    data_ai_hint: 'craftsman bungalow'
  },
  {
    id: '33',
    title: 'Waterfront Luxury Condo',
    price: 2100000,
    address: '33 Waterway, Beachtown, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2300,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Condo',
    description: 'A luxurious condo right on the water. Enjoy marina views from your private balcony. Building includes a private yacht club.',
    amenities: ['Waterfront', 'Marina View', 'Yacht Club Access'],
    agentId: '3',
    data_ai_hint: 'waterfront condo'
  },
  {
    id: '34',
    title: 'Sprawling Suburban Estate',
    price: 1900000,
    address: '34 Grandview Dr, Suburbia, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 5500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A large suburban estate with a pool, tennis court, and manicured gardens. Perfect for entertaining.',
    amenities: ['Swimming Pool', 'Tennis Court', 'Manicured Gardens'],
    agentId: '1',
    data_ai_hint: 'suburban estate'
  },
  {
    id: '35',
    title: 'Cozy Log Cabin',
    price: 550000,
    address: '35 Pine Cone Path, Woodland, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A classic log cabin perfect for a mountain getaway. Features rustic decor and a wood-burning stove.',
    amenities: ['Log Cabin Construction', 'Wood-burning Stove', 'Mountain Setting'],
    agentId: '2',
    data_ai_hint: 'log cabin'
  },
  {
    id: '36',
    title: 'Contemporary Glass House',
    price: 3800000,
    address: '36 Crystal Clear, Modern Hills, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 4200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A spectacular contemporary home made almost entirely of glass, offering seamless indoor-outdoor living.',
    amenities: ['Glass Walls', 'Indoor-Outdoor Living', 'Infinity Pool'],
    agentId: '3',
    data_ai_hint: 'modern glass house'
  },
  {
    id: '37',
    title: 'Duplex with Rental Income',
    price: 850000,
    address: '37 Two-Door Terrace, Anytown, USA',
    bedrooms: 4,
    bathrooms: 2,
    area: 2600,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A fantastic investment opportunity. Live in one unit and rent out the other. Both units have been recently updated.',
    amenities: ['Rental Income', 'Separate Entrances', 'Updated Units'],
    agentId: '1',
    data_ai_hint: 'duplex house'
  },
  {
    id: '38',
    title: 'Urban Micro-Loft',
    price: 395000,
    address: '38 Compact Corner, Metropolis, USA',
    bedrooms: 0,
    bathrooms: 1,
    area: 450,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A cleverly designed micro-loft that makes the most of its small footprint. Perfect for the urban minimalist.',
    amenities: ['Smart Design', 'Central Location', 'Low Maintenance'],
    agentId: '2',
    data_ai_hint: 'small apartment'
  },
  {
    id: '39',
    title: 'Classic Colonial Home',
    price: 1100000,
    address: '39 Independence Way, Historyville, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 3800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A beautiful Colonial home with a grand staircase and formal living and dining rooms. A timeless classic.',
    amenities: ['Colonial Architecture', 'Grand Staircase', 'Formal Dining Room'],
    agentId: '3',
    data_ai_hint: 'colonial house'
  },
  {
    id: '40',
    title: 'Ski Chalet',
    price: 1300000,
    address: '40 Snowflake Summit, Mountaintop, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A cozy and luxurious ski chalet with direct access to the slopes. Features a sauna and a large stone fireplace.',
    amenities: ['Ski-in/Ski-out', 'Sauna', 'Stone Fireplace'],
    agentId: '1',
    data_ai_hint: 'ski chalet'
  },
  {
    id: '41',
    title: 'Renovated Warehouse Loft',
    price: 1250000,
    address: '41 Industrial Way, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 2800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A stunning loft in a renovated warehouse with concrete floors, exposed ductwork, and a chef\'s kitchen.',
    amenities: ['Concrete Floors', 'Exposed Ductwork', 'Chef\'s Kitchen'],
    agentId: '2',
    data_ai_hint: 'warehouse loft'
  },
  {
    id: '42',
    title: 'Gated Community Villa',
    price: 2400000,
    address: '42 Secure Circle, Greenside, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4600,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Villa',
    description: 'A beautiful villa in an exclusive gated community. Offers privacy, security, and access to community amenities.',
    amenities: ['Gated Community', '24/7 Security', 'Community Pool & Tennis'],
    agentId: '3',
    data_ai_hint: 'luxury villa'
  },
  {
    id: '43',
    title: 'Charming Cape Cod',
    price: 880000,
    address: '43 Seaside Street, Beachtown, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2400,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A classic Cape Cod style home with a charming garden, just a short walk from the beach.',
    amenities: ['Cape Cod Style', 'Walk to Beach', 'Charming Garden'],
    agentId: '1',
    data_ai_hint: 'cape cod house'
  },
  {
    id: '44',
    title: 'Downtown Live/Work Space',
    price: 950000,
    address: '44 Enterprise Esplanade, Anytown, USA',
    bedrooms: 1,
    bathrooms: 2,
    area: 2200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A flexible live/work space with a storefront and a modern apartment in the back. Perfect for entrepreneurs.',
    amenities: ['Live/Work Space', 'Storefront', 'Modern Apartment'],
    agentId: '2',
    data_ai_hint: 'live work space'
  },
  {
    id: '45',
    title: 'Hillside Home with Views',
    price: 1600000,
    address: '45 Overlook Trail, Hillside, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A stunning home built into a hillside, with panoramic views of the city and valley below.',
    amenities: ['Panoramic Views', 'Hillside Location', 'Multi-level Decks'],
    agentId: '3',
    data_ai_hint: 'hillside house'
  },
  {
    id: '46',
    title: 'Elegant Pre-War Apartment',
    price: 1400000,
    address: '46 Classic Avenue, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'An elegant apartment in a pre-war building, featuring high ceilings, crown molding, and a formal dining room.',
    amenities: ['Pre-War Building', 'High Ceilings', 'Crown Molding'],
    agentId: '1',
    data_ai_hint: 'classic apartment'
  },
  {
    id: '47',
    title: 'Countryside Barn Conversion',
    price: 1350000,
    address: '47 Haybale Way, Countryside, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 3200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A unique and spacious home that was once a barn. Features soaring ceilings and rustic wood beams.',
    amenities: ['Barn Conversion', 'Soaring Ceilings', 'Wood Beams'],
    agentId: '2',
    data_ai_hint: 'barn house'
  },
  {
    id: '48',
    title: 'Mid-Century Modern Gem',
    price: 1700000,
    address: '48 Retro Road, Suburbia, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A perfectly preserved mid-century modern home, with clean lines, large windows, and an open floor plan.',
    amenities: ['Mid-Century Modern', 'Open Floor Plan', 'Large Windows'],
    agentId: '3',
    data_ai_hint: 'mid century house'
  },
  {
    id: '49',
    title: 'Rooftop Garden Condo',
    price: 980000,
    address: '49 Green Top, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Condo',
    description: 'A beautiful condo with access to a shared rooftop garden, offering a green oasis in the city.',
    amenities: ['Rooftop Garden', 'City Views', 'Community Grills'],
    agentId: '1',
    data_ai_hint: 'rooftop garden'
  },
  {
    id: '50',
    title: 'Luxury Townhouse with Elevator',
    price: 2200000,
    address: '50 Uptown Terrace, Metropolis, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 3800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'An elegant townhouse with a private elevator, gourmet kitchen, and rooftop deck.',
    amenities: ['Private Elevator', 'Rooftop Deck', 'Gourmet Kitchen'],
    agentId: '2',
    data_ai_hint: 'luxury townhouse'
  },
  {
    id: '51',
    title: 'Lake Arrowhead Getaway',
    price: 899000,
    address: '51 Alpine Drive, Lake Arrowhead, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'Your perfect mountain and lake retreat. This cozy cabin offers lake rights and a boat dock.',
    amenities: ['Lake Rights', 'Boat Dock', 'A-Frame Architecture'],
    agentId: '3',
    data_ai_hint: 'mountain cabin'
  },
  {
    id: '52',
    title: 'Beverly Hills Modern Estate',
    price: 12500000,
    address: '52 Rodeo Drive, Beverly Hills, USA',
    bedrooms: 6,
    bathrooms: 8,
    area: 9500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A brand new modern estate in the heart of Beverly Hills. Features an infinity pool and a 10-car garage.',
    amenities: ['Infinity Pool', '10-Car Garage', 'Home Theater', 'City Views'],
    agentId: '1',
    data_ai_hint: 'modern mansion'
  },
  {
    id: '53',
    title: 'Venice Beach Architectural',
    price: 4800000,
    address: '53 Abbot Kinney, Venice, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A stunning architectural home just steps from Abbot Kinney Blvd. Features soaring ceilings and a rooftop deck with ocean views.',
    amenities: ['Rooftop Deck', 'Ocean Views', 'Walking distance to shops'],
    agentId: '2',
    data_ai_hint: 'modern beach house'
  },
  {
    id: '54',
    title: 'Downtown LA Arts District Loft',
    price: 1650000,
    address: '54 Arts District, Los Angeles, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 2200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A spacious loft in the vibrant Arts District. Features polished concrete floors and a communal rooftop pool.',
    amenities: ['Rooftop Pool', 'Polished Concrete Floors', 'Exposed Brick'],
    agentId: '3',
    data_ai_hint: 'artsy loft'
  },
  {
    id: '55',
    title: 'Malibu Beachfront Property',
    price: 9800000,
    address: '55 Pacific Coast Hwy, Malibu, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 4800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'An incredible beachfront home on the sands of Malibu. Features a large deck, private beach access, and stunning sunset views.',
    amenities: ['Private Beach Access', 'Oceanfront Deck', 'Sunset Views'],
    agentId: '1',
    data_ai_hint: 'malibu beach house'
  },
  {
    id: '56',
    title: 'Hollywood Hills View Home',
    price: 6200000,
    address: '56 Stargazer Lane, Hollywood Hills, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 4100,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A celebrity-style home in the Hollywood Hills with jetliner views of the city. Features a screening room and infinity pool.',
    amenities: ['City Views', 'Infinity Pool', 'Screening Room'],
    agentId: '2',
    data_ai_hint: 'hollywood hills house'
  },
  {
    id: '57',
    title: 'Santa Monica Craftsman',
    price: 3200000,
    address: '57 Montana Ave, Santa Monica, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'Charming Craftsman home north of Montana. Walking distance to the beach and shops.',
    amenities: ['Walk to beach', 'Gourmet Kitchen', 'Landscaped Backyard'],
    agentId: '3',
    data_ai_hint: 'craftsman house'
  },
  {
    id: '58',
    title: 'Pasadena Spanish Revival',
    price: 2800000,
    address: '58 Orange Grove, Pasadena, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'Historic Spanish Revival estate with a courtyard, pool, and original details.',
    amenities: ['Courtyard', 'Swimming Pool', 'Historic Landmark'],
    agentId: '1',
    data_ai_hint: 'spanish revival house'
  },
  {
    id: '59',
    title: 'Silver Lake Modern',
    price: 2100000,
    address: '59 Reservoir Rd, Silver Lake, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2400,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'Sleek modern home with views of the Silver Lake reservoir. Features an open floor plan and designer finishes.',
    amenities: ['Reservoir Views', 'Open Floor Plan', 'Designer Kitchen'],
    agentId: '2',
    data_ai_hint: 'modern house'
  },
  {
    id: '60',
    title: 'Echo Park Bungalow',
    price: 1100000,
    address: '60 Park Ave, Echo Park, USA',
    bedrooms: 2,
    bathrooms: 1,
    area: 1100,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A renovated bungalow with a private yard, close to Elysian Park.',
    amenities: ['Private Yard', 'Renovated', 'Close to Park'],
    agentId: '3',
    data_ai_hint: 'cute bungalow'
  },
  {
    id: '61',
    title: 'Newport Beach Bayfront',
    price: 8500000,
    address: '61 Lido Isle, Newport Beach, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 5500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A stunning bayfront home with a private dock for a large yacht.',
    amenities: ['Bayfront', 'Private Dock', 'Guest House'],
    agentId: '1',
    data_ai_hint: 'bayfront mansion'
  },
  {
    id: '62',
    title: 'Laguna Beach Cottage',
    price: 3500000,
    address: '62 Ocean View, Laguna Beach, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A charming cottage with ocean views and a short walk to the village.',
    amenities: ['Ocean Views', 'Walk to Village', 'Artist Studio'],
    agentId: '2',
    data_ai_hint: 'beach cottage'
  },
  {
    id: '63',
    title: 'Irvine Family Home',
    price: 1800000,
    address: '63 University Dr, Irvine, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A beautiful family home in a top-rated school district with community amenities.',
    amenities: ['Top Schools', 'Community Pool', 'Cul-de-sac'],
    agentId: '3',
    data_ai_hint: 'suburban home'
  },
  {
    id: '64',
    title: 'Palm Springs Mid-Century',
    price: 1500000,
    address: '64 Twin Palms, Palm Springs, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'An iconic mid-century modern home with a pool and mountain views.',
    amenities: ['Pool', 'Mountain Views', 'Mid-Century Design'],
    agentId: '1',
    data_ai_hint: 'mid century modern'
  },
  {
    id: '65',
    title: 'Joshua Tree Desert Retreat',
    price: 950000,
    address: '65 Boulder Rd, Joshua Tree, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1600,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A unique desert home with stunning rock formations and starry night skies.',
    amenities: ['Stargazing Deck', 'Desert Landscape', 'Fire Pit'],
    agentId: '2',
    data_ai_hint: 'desert home'
  },
  {
    id: '66',
    title: 'Big Bear Lake Cabin',
    price: 750000,
    address: '66 Bear Mountain, Big Bear, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1700,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A cozy cabin near the ski slopes, perfect for a winter getaway.',
    amenities: ['Hot Tub', 'Near Ski Resort', 'Wood-burning Fireplace'],
    agentId: '3',
    data_ai_hint: 'ski cabin'
  },
  {
    id: '67',
    title: 'San Diego Downtown Condo',
    price: 1250000,
    address: '67 Gaslamp Quarter, San Diego, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Condo',
    description: 'A modern condo in the heart of the Gaslamp Quarter, with city views and building amenities.',
    amenities: ['City Views', 'Rooftop Pool', 'Fitness Center'],
    agentId: '1',
    data_ai_hint: 'city condo'
  },
  {
    id: '68',
    title: 'La Jolla Oceanfront Estate',
    price: 15000000,
    address: '68 Cove Way, La Jolla, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 8000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'An incredible oceanfront estate with a private cove and panoramic views.',
    amenities: ['Private Beach', 'Infinity Pool', 'Wine Cellar'],
    agentId: '2',
    data_ai_hint: 'oceanfront mansion'
  },
  {
    id: '69',
    title: 'San Francisco Victorian',
    price: 4500000,
    address: '69 Alamo Square, San Francisco, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 3800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A classic "Painted Lady" Victorian with views of Alamo Square Park.',
    amenities: ['Historic Home', 'City Views', 'Modern Kitchen'],
    agentId: '3',
    data_ai_hint: 'victorian house'
  },
  {
    id: '70',
    title: 'Napa Valley Vineyard Estate',
    price: 11000000,
    address: '70 Grapevine Rd, Napa, USA',
    bedrooms: 7,
    bathrooms: 8,
    area: 10000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A sprawling estate with its own vineyard, wine cave, and luxury amenities.',
    amenities: ['Vineyard', 'Wine Cave', 'Tennis Court', 'Guest House'],
    agentId: '1',
    data_ai_hint: 'vineyard estate'
  },
  {
    id: '71',
    title: 'Sonoma Farmhouse',
    price: 3800000,
    address: '71 County Line, Sonoma, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A beautiful modern farmhouse with a guest barn and pool.',
    amenities: ['Pool', 'Guest Barn', 'Vegetable Garden'],
    agentId: '2',
    data_ai_hint: 'modern farmhouse'
  },
  {
    id: '72',
    title: 'Lake Tahoe Lakefront',
    price: 9500000,
    address: '72 Emerald Bay, Lake Tahoe, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 6500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A magnificent lakefront estate on the shores of Lake Tahoe with a private pier.',
    amenities: ['Lakefront', 'Private Pier', 'Home Theater', 'Sauna'],
    agentId: '3',
    data_ai_hint: 'lakefront mansion'
  },
  {
    id: '73',
    title: 'Pacific Heights Mansion',
    price: 18000000,
    address: '73 Billionaire Row, San Francisco, USA',
    bedrooms: 8,
    bathrooms: 10,
    area: 12000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'An elegant mansion in Pacific Heights with Golden Gate Bridge views.',
    amenities: ['Golden Gate Views', 'Ballroom', 'Indoor Pool', 'Staff Quarters'],
    agentId: '1',
    data_ai_hint: 'classic mansion'
  },
  {
    id: '74',
    title: 'Sausalito Houseboat',
    price: 1200000,
    address: '74 Waldo Point, Sausalito, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A unique and artistic houseboat with stunning bay views.',
    amenities: ['Bay Views', 'Unique Architecture', 'Waterfront Living'],
    agentId: '2',
    data_ai_hint: 'houseboat interior'
  },
  {
    id: '75',
    title: 'Aspen Ski-In/Ski-Out',
    price: 15000000,
    address: '75 Aspen Mountain, Aspen, USA',
    bedrooms: 7,
    bathrooms: 9,
    area: 9000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A luxurious ski-in/ski-out estate with a bowling alley and indoor spa.',
    amenities: ['Ski-In/Ski-Out', 'Bowling Alley', 'Indoor Spa', 'Mountain Views'],
    agentId: '3',
    data_ai_hint: 'luxury ski chalet'
  },
  {
    id: '76',
    title: 'Miami Beach Penthouse',
    price: 10500000,
    address: '76 South Beach, Miami, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 6000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Condo',
    description: 'A stunning penthouse with a private rooftop pool and 360-degree ocean views.',
    amenities: ['Rooftop Pool', 'Ocean Views', 'Private Elevator', '24/7 Concierge'],
    agentId: '1',
    data_ai_hint: 'miami penthouse'
  },
  {
    id: '77',
    title: 'Austin Modern Farmhouse',
    price: 2500000,
    address: '77 South Congress, Austin, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A chic modern farmhouse in the heart of Austin\'s trendiest neighborhood.',
    amenities: ['Pool', 'Outdoor Kitchen', 'Walk to shops'],
    agentId: '2',
    data_ai_hint: 'modern farmhouse'
  },
  {
    id: '78',
    title: 'NYC Soho Loft',
    price: 7800000,
    address: '78 Mercer Street, New York, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 3500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A classic cast-iron loft in Soho with high ceilings and a private keyed elevator.',
    amenities: ['Keyed Elevator', 'High Ceilings', 'Exposed Brick'],
    agentId: '3',
    data_ai_hint: 'soho loft'
  },
  {
    id: '79',
    title: 'Hamptons Beach House',
    price: 9200000,
    address: '79 Dune Road, The Hamptons, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 5200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A beautiful oceanfront beach house with a pool, tennis court, and private beach access.',
    amenities: ['Oceanfront', 'Pool', 'Tennis Court', 'Private Beach'],
    agentId: '1',
    data_ai_hint: 'hamptons house'
  },
  {
    id: '80',
    title: 'Seattle Waterfront Home',
    price: 4800000,
    address: '80 Lake Washington, Seattle, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A contemporary waterfront home with a private dock and views of the city skyline.',
    amenities: ['Waterfront', 'Private Dock', 'City Views', 'Wine Cellar'],
    agentId: '2',
    data_ai_hint: 'seattle waterfront'
  },
  {
    id: '81',
    title: 'Boston Brownstone',
    price: 6500000,
    address: '81 Beacon Street, Boston, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 5000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'An elegant brownstone on a picturesque street in Beacon Hill.',
    amenities: ['Historic', 'Rooftop Deck', 'Garden', 'Au Pair Suite'],
    agentId: '3',
    data_ai_hint: 'boston brownstone'
  },
  {
    id: '82',
    title: 'Chicago Gold Coast Condo',
    price: 3800000,
    address: '82 Lake Shore Drive, Chicago, USA',
    bedrooms: 3,
    bathrooms: 4,
    area: 3200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Condo',
    description: 'A luxury condo with stunning lake views and high-end finishes.',
    amenities: ['Lake Views', 'Valet Parking', 'Indoor Pool', 'Fitness Center'],
    agentId: '1',
    data_ai_hint: 'chicago condo'
  },
  {
    id: '83',
    title: 'Scottsdale Golf Estate',
    price: 5200000,
    address: '83 Whisper Rock, Scottsdale, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 6500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A custom estate on a private golf course with a resort-style backyard.',
    amenities: ['Golf Course', 'Resort Pool', 'Home Theater', 'Casita'],
    agentId: '2',
    data_ai_hint: 'scottsdale mansion'
  },
  {
    id: '84',
    title: 'Hawaiian Oceanfront Villa',
    price: 12000000,
    address: '84 North Shore, Oahu, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 7500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Villa',
    description: 'A breathtaking oceanfront villa with direct beach access and an infinity pool.',
    amenities: ['Oceanfront', 'Infinity Pool', 'Tropical Gardens', 'Gourmet Kitchen'],
    agentId: '3',
    data_ai_hint: 'hawaii villa'
  },
  {
    id: '85',
    title: 'Montana Ranch',
    price: 7500000,
    address: '85 Big Sky, Montana, USA',
    bedrooms: 8,
    bathrooms: 10,
    area: 12000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A massive luxury ranch on hundreds of acres with a main lodge and guest cabins.',
    amenities: ['Acreage', 'Horse Stables', 'Fishing Pond', 'Mountain Views'],
    agentId: '1',
    data_ai_hint: 'luxury ranch'
  },
  {
    id: '86',
    title: 'Key West Conch House',
    price: 2200000,
    address: '86 Duval Street, Key West, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 2800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A historic Conch-style house with a pool and lush tropical gardens.',
    amenities: ['Pool', 'Tropical Garden', 'Historic District', 'Guest Cottage'],
    agentId: '2',
    data_ai_hint: 'key west house'
  },
  {
    id: '87',
    title: 'New Orleans French Quarter',
    price: 3100000,
    address: '87 Royal Street, New Orleans, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'An elegant townhouse with a private courtyard in the heart of the French Quarter.',
    amenities: ['Courtyard', 'Balconies', 'Historic', 'Gourmet Kitchen'],
    agentId: '3',
    data_ai_hint: 'new orleans townhouse'
  },
  {
    id: '88',
    title: 'Las Vegas Penthouse',
    price: 6800000,
    address: '88 The Strip, Las Vegas, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 5500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Condo',
    description: 'A spectacular penthouse with panoramic views of the Las Vegas Strip.',
    amenities: ['Strip Views', 'Rooftop Pool', '24/7 Butler Service', 'Screening Room'],
    agentId: '1',
    data_ai_hint: 'vegas penthouse'
  },
  {
    id: '89',
    title: 'Portland Craftsman',
    price: 1300000,
    address: '89 NW 23rd, Portland, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 3100,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A beautifully restored Craftsman home in a vibrant, walkable neighborhood.',
    amenities: ['Restored Woodwork', 'Walkable', 'Finished Basement', 'Garden'],
    agentId: '2',
    data_ai_hint: 'portland house'
  },
  {
    id: '90',
    title: 'Charleston Single House',
    price: 2800000,
    address: '90 South of Broad, Charleston, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A grand historic single house with double piazzas and a walled garden.',
    amenities: ['Piazzas', 'Walled Garden', 'Historic', 'Guest Suite'],
    agentId: '3',
    data_ai_hint: 'charleston house'
  },
  {
    id: '91',
    title: 'Nashville Music Row Home',
    price: 1900000,
    address: '91 Music Square, Nashville, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3600,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A contemporary home with a recording studio near Music Row.',
    amenities: ['Recording Studio', 'Rooftop Deck', 'Modern Design'],
    agentId: '1',
    data_ai_hint: 'nashville home'
  },
  {
    id: '92',
    title: 'Savannah Historic District',
    price: 2400000,
    address: '92 Forsyth Park, Savannah, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'An elegant townhouse overlooking Forsyth Park with a carriage house.',
    amenities: ['Park View', 'Carriage House', 'Courtyard Garden', 'Historic'],
    agentId: '2',
    data_ai_hint: 'savannah house'
  },
  {
    id: '93',
    title: 'Texas Hill Country Ranch',
    price: 4800000,
    address: '93 Lone Star Trail, Hill Country, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 8000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A sprawling ranch with a custom home, pool, and guest lodge on 100 acres.',
    amenities: ['100 Acres', 'Pool', 'Guest Lodge', 'Horse Barn'],
    agentId: '3',
    data_ai_hint: 'texas ranch'
  },
  {
    id: '94',
    title: 'Washington D.C. Rowhouse',
    price: 3200000,
    address: '94 Capitol Hill, Washington D.C., USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A beautifully renovated Federal rowhouse on Capitol Hill.',
    amenities: ['Renovated', 'Rooftop Deck', 'English Basement', 'Historic'],
    agentId: '1',
    data_ai_hint: 'dc rowhouse'
  },
  {
    id: '95',
    title: 'Philadelphia Trinity House',
    price: 850000,
    address: '95 Elfreth\'s Alley, Philadelphia, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A charming and historic Trinity house on America\'s oldest residential street.',
    amenities: ['Historic', 'Spiral Staircase', 'Cobblestone Street'],
    agentId: '2',
    data_ai_hint: 'historic house'
  },
  {
    id: '96',
    title: 'Salt Lake City Mountain Home',
    price: 2900000,
    address: '96 Wasatch Blvd, Salt Lake City, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 5500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A modern mountain home with panoramic views of the valley and mountains.',
    amenities: ['Valley Views', 'Mountain Views', 'Home Gym', 'Theater'],
    agentId: '3',
    data_ai_hint: 'mountain modern'
  },
  {
    id: '97',
    title: 'Atlanta Buckhead Estate',
    price: 8900000,
    address: '97 Tuxedo Park, Atlanta, USA',
    bedrooms: 7,
    bathrooms: 9,
    area: 11000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A grand estate in the heart of Buckhead with a pool, tennis court, and formal gardens.',
    amenities: ['Pool', 'Tennis Court', 'Formal Gardens', 'Guest House'],
    agentId: '1',
    data_ai_hint: 'luxury estate'
  },
  {
    id: '98',
    title: 'Denver LoHi Duplex',
    price: 1500000,
    address: '98 Platte Street, Denver, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2600,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A stylish duplex with a rooftop deck and city views in the Lower Highlands.',
    amenities: ['Rooftop Deck', 'City Views', 'Modern Finishes', 'Walkable'],
    agentId: '2',
    data_ai_hint: 'modern duplex'
  },
  {
    id: '99',
    title: 'Rural Vermont Farmhouse',
    price: 1200000,
    address: '99 Green Mountain, Vermont, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 3500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A classic farmhouse on 50 acres with a large barn and rolling hills.',
    amenities: ['50 Acres', 'Barn', 'Mountain Views', 'Fireplace'],
    agentId: '3',
    data_ai_hint: 'vermont farmhouse'
  },
  {
    id: '100',
    title: 'Maine Coastal Compound',
    price: 5800000,
    address: '100 Ocean Point, Kennebunkport, USA',
    bedrooms: 8,
    bathrooms: 9,
    area: 9000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A magnificent coastal compound with a main house, guest house, and deep water dock.',
    amenities: ['Oceanfront', 'Deep Water Dock', 'Guest House', 'Pool'],
    agentId: '1',
    data_ai_hint: 'coastal estate'
  },
  {
    id: '101',
    title: 'Upstate NY Lake House',
    price: 2100000,
    address: '101 Finger Lakes, New York, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 4000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A beautiful lake house with a private dock and stunning water views.',
    amenities: ['Lakefront', 'Private Dock', 'Wine Cellar', 'Fire Pit'],
    agentId: '2',
    data_ai_hint: 'lake house'
  },
  {
    id: '102',
    title: 'Brooklyn Brownstone',
    price: 4200000,
    address: '102 Park Slope, Brooklyn, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 3800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A renovated brownstone in Park Slope with original details and a modern kitchen.',
    amenities: ['Original Details', 'Modern Kitchen', 'Garden', 'Roof Deck'],
    agentId: '3',
    data_ai_hint: 'brooklyn brownstone'
  },
  {
    id: '103',
    title: 'Greenwich CT Grand Estate',
    price: 14500000,
    address: '103 Round Hill, Greenwich, USA',
    bedrooms: 7,
    bathrooms: 10,
    area: 13000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A stately brick Georgian on a private lane with a pool, tennis court, and guest house.',
    amenities: ['Pool', 'Tennis Court', 'Guest House', 'Formal Gardens'],
    agentId: '1',
    data_ai_hint: 'georgian estate'
  },
  {
    id: '104',
    title: 'Cambridge Historic Home',
    price: 3900000,
    address: '104 Brattle Street, Cambridge, USA',
    bedrooms: 6,
    bathrooms: 5,
    area: 5200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A significant historic home near Harvard Square with a large yard and carriage house.',
    amenities: ['Historic', 'Carriage House', 'Large Yard', 'Library'],
    agentId: '2',
    data_ai_hint: 'historic home'
  },
  {
    id: '105',
    title: 'New Mexico Adobe Home',
    price: 1600000,
    address: '105 Canyon Road, Santa Fe, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 3000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'An authentic adobe home with kiva fireplaces, vigas, and a private courtyard.',
    amenities: ['Adobe Construction', 'Kiva Fireplaces', 'Courtyard', 'Mountain Views'],
    agentId: '3',
    data_ai_hint: 'adobe home'
  },
  {
    id: '106',
    title: 'Florida Keys Private Island',
    price: 25000000,
    address: '106 Paradise Cay, Florida Keys, USA',
    bedrooms: 10,
    bathrooms: 12,
    area: 15000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Villa',
    description: 'Your own private island with a main residence, guest villas, and a deep water marina.',
    amenities: ['Private Island', 'Deep Water Marina', 'Heli-Pad', 'Staff Quarters'],
    agentId: '1',
    data_ai_hint: 'private island'
  }
];

const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'John & Jane Doe',
    company: 'Happy Homeowners',
    comment: 'RealEstate Explorer helped us find our dream home in just a week! The process was seamless and the agents were incredibly professional. We couldn\'t be happier.',
    image: 'https://placehold.co/100x100.png',
    data_ai_hint: "happy couple"
  },
  {
    id: '2',
    name: 'Peter Jones',
    company: 'First-Time Buyer',
    comment: 'As a first-time buyer, I was nervous about the process. The team at RealEstate Explorer guided me every step of the way. Highly recommended!',
    image: 'https://placehold.co/100x100.png',
    data_ai_hint: "smiling man"
  },
  {
    id: '3',
    name: 'Mary Smith',
    company: 'Property Investor',
    comment: 'I\'ve worked with many real estate companies, but RealEstate Explorer stands out. Their market knowledge and dedication are top-notch. They helped me find a great investment property.',
    image: 'https://placehold.co/100x100.png',
    data_ai_hint: "business woman"
  },
];

export const getProperties = async (): Promise<Property[]> => {
  return properties;
};

export const getFeaturedProperties = async (): Promise<Property[]> => {
  return properties.filter(p => p.featured);
};

export const getPropertyById = async (id: string): Promise<Property | undefined> => {
  return properties.find(p => p.id === id);
};

export const getAgents = async (): Promise<Agent[]> => {
  return agents;
};

export const getAgentById = async (id: string): Promise<Agent | undefined> => {
  return agents.find(a => a.id === id);
};

export const getTestimonials = async (): Promise<Testimonial[]> => {
  return testimonials;
};
