import type { Property, Agent, Testimonial } from './types';

const agents: Agent[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    title: 'Senior Real Estate Agent',
    phone: '123-456-7890',
    email: 'alice.j@realestate.com',
    image: 'https://placehold.co/400x400.png',
    propertiesCount: 5,
    data_ai_hint: "professional woman"
  },
  {
    id: '2',
    name: 'Bob Williams',
    title: 'Commercial Property Specialist',
    phone: '123-456-7891',
    email: 'bob.w@realestate.com',
    image: 'https://placehold.co/400x400.png',
    propertiesCount: 3,
    data_ai_hint: "professional man"
  },
   {
    id: '3',
    name: 'Charlie Brown',
    title: 'Luxury Home Consultant',
    phone: '123-456-7892',
    email: 'charlie.b@realestate.com',
    image: 'https://placehold.co/400x400.png',
    propertiesCount: 4,
    data_ai_hint: "friendly man"
  },
];

const properties: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Loft',
    price: 1200000,
    address: '123 Main St, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Apartment',
    description: 'A beautiful and spacious loft in the heart of the city. Features high ceilings, large windows, and a modern kitchen. Perfect for urban living.',
    amenities: ['Gym', 'Pool', 'Rooftop Deck', '24/7 Security'],
    agentId: '1',
    data_ai_hint: "modern apartment interior"
  },
  {
    id: '2',
    title: 'Suburban Family Home',
    price: 750000,
    address: '456 Oak Ave, Suburbia, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A charming family home in a quiet suburban neighborhood. Features a large backyard, a two-car garage, and a newly renovated kitchen.',
    amenities: ['Backyard', 'Garage', 'Fireplace', 'Modern Kitchen'],
    agentId: '2',
    data_ai_hint: "suburban house exterior"
  },
  {
    id: '3',
    title: 'Luxury Beachfront Villa',
    price: 3500000,
    address: '789 Ocean Blvd, Beachtown, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 5000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Villa',
    description: 'An exquisite beachfront villa with breathtaking ocean views. Features a private pool, direct beach access, and a home theater.',
    amenities: ['Private Pool', 'Beach Access', 'Home Theater', 'Gourmet Kitchen', 'Ocean View'],
    agentId: '3',
    data_ai_hint: "luxury villa beach"
  },
  {
    id: '4',
    title: 'Cozy Condo with City View',
    price: 550000,
    address: '101 Pine St, Anytown, USA',
    bedrooms: 1,
    bathrooms: 1,
    area: 800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Condo',
    description: 'A cozy and modern condo with a stunning view of the city skyline. Perfect for a young professional or couple. Building includes a gym and pool.',
    amenities: ['Gym', 'Pool', 'Concierge', 'City View'],
    agentId: '1',
    data_ai_hint: "modern condo interior"
  },
  {
    id: '5',
    title: 'Spacious House with Garden',
    price: 850000,
    address: '222 Maple Dr, Suburbia, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 2200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A spacious house with a beautiful garden and outdoor patio. Ideal for families who love the outdoors. Includes a large living room and a formal dining area.',
    amenities: ['Garden', 'Patio', 'Garage', 'Hardwood Floors'],
    agentId: '2',
    data_ai_hint: "house garden"
  },
  {
    id: '6',
    title: 'Penthouse with Rooftop Terrace',
    price: 2500000,
    address: '333 Sky High Rd, Anytown, USA',
    bedrooms: 3,
    bathrooms: 4,
    area: 3000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png', 'https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Apartment',
    description: 'A stunning penthouse apartment with a private rooftop terrace offering 360-degree city views. Luxury finishes throughout.',
    amenities: ['Rooftop Terrace', 'Private Elevator', 'Concierge', ' panoramic views'],
    agentId: '3',
    data_ai_hint: "luxury penthouse interior"
  },
  {
    id: '7',
    title: 'Quaint Cottage in the Woods',
    price: 450000,
    address: '77 Forest Lane, Woodland, USA',
    bedrooms: 2,
    bathrooms: 1,
    area: 1200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A cozy cottage surrounded by nature. Perfect for a peaceful retreat. Features a stone fireplace and a large wooden deck.',
    amenities: ['Fireplace', 'Deck', 'Hiking Trails Access'],
    agentId: '1',
    data_ai_hint: 'cottage woods'
  },
  {
    id: '8',
    title: 'Sleek Urban Studio',
    price: 480000,
    address: '88 City Center, Metropolis, USA',
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Apartment',
    description: 'A stylish and efficient studio in a bustling urban center. Close to public transport and nightlife.',
    amenities: ['Modern Appliances', 'Walk-in Closet', 'Building Security'],
    agentId: '2',
    data_ai_hint: 'urban studio'
  },
  {
    id: '9',
    title: 'Historic Townhouse',
    price: 980000,
    address: '99 Old Town Rd, Historyville, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A beautifully preserved townhouse with historic charm and modern updates. Features original hardwood floors and a private garden.',
    amenities: ['Private Garden', 'Historic Details', 'Renovated Kitchen'],
    agentId: '3',
    data_ai_hint: 'historic townhouse'
  },
  {
    id: '10',
    title: 'Mountain View Condo',
    price: 620000,
    address: '10 Mountain Pass, Summit, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Condo',
    description: 'A comfortable condo with stunning mountain views from every window. Includes access to a community lodge and ski slopes.',
    amenities: ['Mountain View', 'Ski-in/Ski-out', 'Community Hot Tub'],
    agentId: '1',
    data_ai_hint: 'mountain condo'
  },
  {
    id: '11',
    title: 'Riverside Family Retreat',
    price: 1100000,
    address: '111 Riverbend Dr, Riverton, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A large family home on the river. Features a private dock, spacious lawn, and a game room.',
    amenities: ['River Access', 'Private Dock', 'Game Room'],
    agentId: '2',
    data_ai_hint: 'house river'
  },
  {
    id: '12',
    title: 'Eco-Friendly Modern Home',
    price: 1350000,
    address: '12 Solar Way, Greenville, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A state-of-the-art eco-friendly home with solar panels and sustainable materials. Designed for green living without sacrificing luxury.',
    amenities: ['Solar Panels', 'Rainwater Harvesting', 'Smart Home System'],
    agentId: '3',
    data_ai_hint: 'eco friendly house'
  },
  {
    id: '13',
    title: 'Artist Loft with Studio Space',
    price: 890000,
    address: '13 Creative Circle, Artstown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 2000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A spacious loft with high ceilings and a dedicated studio space, perfect for artists and creatives.',
    amenities: ['Studio Space', 'High Ceilings', 'Natural Light'],
    agentId: '1',
    data_ai_hint: 'artist loft'
  },
  {
    id: '14',
    title: 'Downtown High-Rise Apartment',
    price: 1500000,
    address: '1400 Skyline Ave, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Apartment',
    description: 'A luxury apartment on a high floor with panoramic city views. Building has a pool, gym, and 24/7 concierge.',
    amenities: ['Panoramic Views', 'Floor-to-Ceiling Windows', 'Valet Parking'],
    agentId: '2',
    data_ai_hint: 'luxury apartment'
  },
  {
    id: '15',
    title: 'Ranch-Style Country House',
    price: 950000,
    address: '15 Prairie Lane, Countryside, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 3500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A sprawling ranch-style house on a large plot of land. Features horse stables and wide-open spaces.',
    amenities: ['Large Acreage', 'Horse Stables', 'Wraparound Porch'],
    agentId: '3',
    data_ai_hint: 'ranch house'
  },
  {
    id: '16',
    title: 'Lakeside Cabin',
    price: 680000,
    address: '16 Water\'s Edge, Laketown, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A charming cabin with direct lake access. Perfect for fishing, boating, and summer getaways.',
    amenities: ['Lakefront', 'Private Dock', 'Screened Porch'],
    agentId: '1',
    data_ai_hint: 'lake cabin'
  },
  {
    id: '17',
    title: 'Chic Urban Condo',
    price: 720000,
    address: '17 Trendsetter Way, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Condo',
    description: 'A very stylish condo in a trendy neighborhood, known for its boutiques and cafes. Features a balcony and designer finishes.',
    amenities: ['Balcony', 'Designer Finishes', 'Community Lounge'],
    agentId: '2',
    data_ai_hint: 'urban condo'
  },
  {
    id: '18',
    title: 'Mediterranean-Style Villa',
    price: 2800000,
    address: '18 Vineyard Valley, Wine Country, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Villa',
    description: 'An elegant Mediterranean-style villa with a courtyard, fountain, and wine cellar. Set in a beautiful vineyard.',
    amenities: ['Courtyard', 'Wine Cellar', 'Swimming Pool'],
    agentId: '3',
    data_ai_hint: 'mediterranean villa'
  },
  {
    id: '19',
    title: 'Affordable Starter Home',
    price: 350000,
    address: '19 Opportunity Ave, Suburbia, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A perfect and affordable starter home for a new family. Features a fenced-in backyard and is close to schools.',
    amenities: ['Fenced Yard', 'Near Schools', 'Updated Appliances'],
    agentId: '1',
    data_ai_hint: 'starter home'
  },
  {
    id: '20',
    title: 'Industrial Loft Conversion',
    price: 1150000,
    address: '20 Factory Row, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 2400,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A unique loft in a converted factory. Features exposed brick, high ceilings, and industrial details.',
    amenities: ['Exposed Brick', 'High Ceilings', 'Freight Elevator Access'],
    agentId: '2',
    data_ai_hint: 'industrial loft'
  },
  {
    id: '21',
    title: 'Secluded Forest House',
    price: 880000,
    address: '21 Whisperwind Path, Forest, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 3000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A private and secluded home surrounded by dense forest. Perfect for nature lovers seeking tranquility.',
    amenities: ['Secluded', 'Forest Views', 'Hiking Trails'],
    agentId: '3',
    data_ai_hint: 'forest house'
  },
  {
    id: '22',
    title: 'Golf Course Estate',
    price: 4200000,
    address: '22 Fairway Drive, Greenside, USA',
    bedrooms: 6,
    bathrooms: 7,
    area: 7000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'An expansive estate on a prestigious golf course. Features a home gym, theater, and custom pool.',
    amenities: ['Golf Course View', 'Home Gym', 'Theater Room', 'Custom Pool'],
    agentId: '1',
    data_ai_hint: 'luxury house'
  },
  {
    id: '23',
    title: 'Bright and Airy Beach House',
    price: 1750000,
    address: '23 Sandy Lane, Beachtown, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A beautiful beach house with an open floor plan and plenty of natural light. Just steps from the sand.',
    amenities: ['Beach Access', 'Ocean View', 'Outdoor Shower'],
    agentId: '2',
    data_ai_hint: 'beach house'
  },
  {
    id: '24',
    title: 'Penthouse with Private Pool',
    price: 5500000,
    address: '24 Skyline Terrace, Metropolis, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 4800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Apartment',
    description: 'The ultimate in luxury living. This penthouse features a private rooftop pool and unparalleled city views.',
    amenities: ['Private Pool', 'Rooftop Terrace', '360-degree Views', 'Private Chef Kitchen'],
    agentId: '3',
    data_ai_hint: 'luxury penthouse'
  },
  {
    id: '25',
    title: 'Suburban Tudor Home',
    price: 920000,
    address: '25 Tudor Grove, Suburbia, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2700,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'Classic Tudor style home with beautiful architectural details in a family-friendly neighborhood.',
    amenities: ['Landscaped Garden', 'Two-car garage', 'Classic Architecture'],
    agentId: '1',
    data_ai_hint: 'tudor house'
  },
  {
    id: '26',
    title: 'Minimalist City Apartment',
    price: 680000,
    address: '26 Simple Street, Anytown, USA',
    bedrooms: 2,
    bathrooms: 1,
    area: 1100,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A minimalist apartment with clean lines and a focus on simplicity and function. Located in a quiet, yet central area.',
    amenities: ['Minimalist Design', 'Smart Storage', 'Quiet Street'],
    agentId: '2',
    data_ai_hint: 'minimalist apartment'
  },
  {
    id: '27',
    title: 'Desert Modern Home',
    price: 1950000,
    address: '27 Cactus Trail, Desert Springs, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 3200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A stunning modern home in the desert, designed to blend with the landscape. Features a negative-edge pool and amazing sunset views.',
    amenities: ['Desert Landscape', 'Infinity Pool', 'Sunset Views'],
    agentId: '3',
    data_ai_hint: 'desert house'
  },
  {
    id: '28',
    title: 'Garden Apartment',
    price: 650000,
    address: '28 Blossom Court, Greenville, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A lovely ground-floor apartment with a private garden patio. Perfect for those who want outdoor space in the city.',
    amenities: ['Private Garden', 'Ground Floor', 'Pet Friendly'],
    agentId: '1',
    data_ai_hint: 'garden apartment'
  },
  {
    id: '29',
    title: 'Victorian Mansion',
    price: 3200000,
    address: '29 Heritage Hill, Historyville, USA',
    bedrooms: 7,
    bathrooms: 8,
    area: 8000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A grand Victorian mansion, fully restored with meticulous attention to detail. Features a ballroom and servants quarters.',
    amenities: ['Historic Restoration', 'Ballroom', 'Large Estate'],
    agentId: '2',
    data_ai_hint: 'victorian mansion'
  },
  {
    id: '30',
    title: 'Modern Farmhouse',
    price: 1450000,
    address: '30 Country Road, Farmland, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 4000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A new-build modern farmhouse with a classic look and all the modern amenities. Features a gourmet kitchen and a large front porch.',
    amenities: ['Modern Farmhouse Style', 'Gourmet Kitchen', 'Wraparound Porch'],
    agentId: '3',
    data_ai_hint: 'modern farmhouse'
  },
  {
    id: '31',
    title: 'Sky-High City Condo',
    price: 1800000,
    address: '31 Cloud Nine, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Condo',
    description: 'Live in the clouds in this stunning high-rise condo. Features incredible views and five-star building amenities.',
    amenities: ['High Floor', 'City Views', 'Rooftop Pool'],
    agentId: '1',
    data_ai_hint: 'city condo'
  },
  {
    id: '32',
    title: 'Craftsman Bungalow',
    price: 780000,
    address: '32 Arts & Crafts Way, Suburbia, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A charming Craftsman bungalow with a cozy fireplace and built-in cabinetry. A true gem in a quiet neighborhood.',
    amenities: ['Craftsman Style', 'Cozy Fireplace', 'Built-in Shelving'],
    agentId: '2',
    data_ai_hint: 'craftsman bungalow'
  },
  {
    id: '33',
    title: 'Waterfront Luxury Condo',
    price: 2100000,
    address: '33 Waterway, Beachtown, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 2300,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'Condo',
    description: 'A luxurious condo right on the water. Enjoy marina views from your private balcony. Building includes a private yacht club.',
    amenities: ['Waterfront', 'Marina View', 'Yacht Club Access'],
    agentId: '3',
    data_ai_hint: 'waterfront condo'
  },
  {
    id: '34',
    title: 'Sprawling Suburban Estate',
    price: 1900000,
    address: '34 Grandview Dr, Suburbia, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 5500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A large suburban estate with a pool, tennis court, and manicured gardens. Perfect for entertaining.',
    amenities: ['Swimming Pool', 'Tennis Court', 'Manicured Gardens'],
    agentId: '1',
    data_ai_hint: 'suburban estate'
  },
  {
    id: '35',
    title: 'Cozy Log Cabin',
    price: 550000,
    address: '35 Pine Cone Path, Woodland, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A classic log cabin perfect for a mountain getaway. Features rustic decor and a wood-burning stove.',
    amenities: ['Log Cabin Construction', 'Wood-burning Stove', 'Mountain Setting'],
    agentId: '2',
    data_ai_hint: 'log cabin'
  },
  {
    id: '36',
    title: 'Contemporary Glass House',
    price: 3800000,
    address: '36 Crystal Clear, Modern Hills, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 4200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A spectacular contemporary home made almost entirely of glass, offering seamless indoor-outdoor living.',
    amenities: ['Glass Walls', 'Indoor-Outdoor Living', 'Infinity Pool'],
    agentId: '3',
    data_ai_hint: 'modern glass house'
  },
  {
    id: '37',
    title: 'Duplex with Rental Income',
    price: 850000,
    address: '37 Two-Door Terrace, Anytown, USA',
    bedrooms: 4,
    bathrooms: 2,
    area: 2600,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A fantastic investment opportunity. Live in one unit and rent out the other. Both units have been recently updated.',
    amenities: ['Rental Income', 'Separate Entrances', 'Updated Units'],
    agentId: '1',
    data_ai_hint: 'duplex house'
  },
  {
    id: '38',
    title: 'Urban Micro-Loft',
    price: 395000,
    address: '38 Compact Corner, Metropolis, USA',
    bedrooms: 0,
    bathrooms: 1,
    area: 450,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A cleverly designed micro-loft that makes the most of its small footprint. Perfect for the urban minimalist.',
    amenities: ['Smart Design', 'Central Location', 'Low Maintenance'],
    agentId: '2',
    data_ai_hint: 'small apartment'
  },
  {
    id: '39',
    title: 'Classic Colonial Home',
    price: 1100000,
    address: '39 Independence Way, Historyville, USA',
    bedrooms: 5,
    bathrooms: 4,
    area: 3800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A beautiful Colonial home with a grand staircase and formal living and dining rooms. A timeless classic.',
    amenities: ['Colonial Architecture', 'Grand Staircase', 'Formal Dining Room'],
    agentId: '3',
    data_ai_hint: 'colonial house'
  },
  {
    id: '40',
    title: 'Ski Chalet',
    price: 1300000,
    address: '40 Snowflake Summit, Mountaintop, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A cozy and luxurious ski chalet with direct access to the slopes. Features a sauna and a large stone fireplace.',
    amenities: ['Ski-in/Ski-out', 'Sauna', 'Stone Fireplace'],
    agentId: '1',
    data_ai_hint: 'ski chalet'
  },
  {
    id: '41',
    title: 'Renovated Warehouse Loft',
    price: 1250000,
    address: '41 Industrial Way, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 2800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A stunning loft in a renovated warehouse with concrete floors, exposed ductwork, and a chef\'s kitchen.',
    amenities: ['Concrete Floors', 'Exposed Ductwork', 'Chef\'s Kitchen'],
    agentId: '2',
    data_ai_hint: 'warehouse loft'
  },
  {
    id: '42',
    title: 'Gated Community Villa',
    price: 2400000,
    address: '42 Secure Circle, Greenside, USA',
    bedrooms: 5,
    bathrooms: 5,
    area: 4600,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Villa',
    description: 'A beautiful villa in an exclusive gated community. Offers privacy, security, and access to community amenities.',
    amenities: ['Gated Community', '24/7 Security', 'Community Pool & Tennis'],
    agentId: '3',
    data_ai_hint: 'luxury villa'
  },
  {
    id: '43',
    title: 'Charming Cape Cod',
    price: 880000,
    address: '43 Seaside Street, Beachtown, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2400,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A classic Cape Cod style home with a charming garden, just a short walk from the beach.',
    amenities: ['Cape Cod Style', 'Walk to Beach', 'Charming Garden'],
    agentId: '1',
    data_ai_hint: 'cape cod house'
  },
  {
    id: '44',
    title: 'Downtown Live/Work Space',
    price: 950000,
    address: '44 Enterprise Esplanade, Anytown, USA',
    bedrooms: 1,
    bathrooms: 2,
    area: 2200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'A flexible live/work space with a storefront and a modern apartment in the back. Perfect for entrepreneurs.',
    amenities: ['Live/Work Space', 'Storefront', 'Modern Apartment'],
    agentId: '2',
    data_ai_hint: 'live work space'
  },
  {
    id: '45',
    title: 'Hillside Home with Views',
    price: 1600000,
    address: '45 Overlook Trail, Hillside, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A stunning home built into a hillside, with panoramic views of the city and valley below.',
    amenities: ['Panoramic Views', 'Hillside Location', 'Multi-level Decks'],
    agentId: '3',
    data_ai_hint: 'hillside house'
  },
  {
    id: '46',
    title: 'Elegant Pre-War Apartment',
    price: 1400000,
    address: '46 Classic Avenue, Metropolis, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Apartment',
    description: 'An elegant apartment in a pre-war building, featuring high ceilings, crown molding, and a formal dining room.',
    amenities: ['Pre-War Building', 'High Ceilings', 'Crown Molding'],
    agentId: '1',
    data_ai_hint: 'classic apartment'
  },
  {
    id: '47',
    title: 'Countryside Barn Conversion',
    price: 1350000,
    address: '47 Haybale Way, Countryside, USA',
    bedrooms: 3,
    bathrooms: 3,
    area: 3200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A unique and spacious home that was once a barn. Features soaring ceilings and rustic wood beams.',
    amenities: ['Barn Conversion', 'Soaring Ceilings', 'Wood Beams'],
    agentId: '2',
    data_ai_hint: 'barn house'
  },
  {
    id: '48',
    title: 'Mid-Century Modern Gem',
    price: 1700000,
    address: '48 Retro Road, Suburbia, USA',
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A perfectly preserved mid-century modern home, with clean lines, large windows, and an open floor plan.',
    amenities: ['Mid-Century Modern', 'Open Floor Plan', 'Large Windows'],
    agentId: '3',
    data_ai_hint: 'mid century house'
  },
  {
    id: '49',
    title: 'Rooftop Garden Condo',
    price: 980000,
    address: '49 Green Top, Anytown, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Condo',
    description: 'A beautiful condo with access to a shared rooftop garden, offering a green oasis in the city.',
    amenities: ['Rooftop Garden', 'City Views', 'Community Grills'],
    agentId: '1',
    data_ai_hint: 'rooftop garden'
  },
  {
    id: '50',
    title: 'Luxury Townhouse with Elevator',
    price: 2200000,
    address: '50 Uptown Terrace, Metropolis, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 3800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'An elegant townhouse with a private elevator, gourmet kitchen, and rooftop deck.',
    amenities: ['Private Elevator', 'Rooftop Deck', 'Gourmet Kitchen'],
    agentId: '2',
    data_ai_hint: 'luxury townhouse'
  },
  {
    id: '51',
    title: 'Lake Arrowhead Getaway',
    price: 899000,
    address: '51 Alpine Drive, Lake Arrowhead, USA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'Your perfect mountain and lake retreat. This cozy cabin offers lake rights and a boat dock.',
    amenities: ['Lake Rights', 'Boat Dock', 'A-Frame Architecture'],
    agentId: '3',
    data_ai_hint: 'mountain cabin'
  },
  {
    id: '52',
    title: 'Beverly Hills Modern Estate',
    price: 12500000,
    address: '52 Rodeo Drive, Beverly Hills, USA',
    bedrooms: 6,
    bathrooms: 8,
    area: 9500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A brand new modern estate in the heart of Beverly Hills. Features an infinity pool and a 10-car garage.',
    amenities: ['Infinity Pool', '10-Car Garage', 'Home Theater', 'City Views'],
    agentId: '1',
    data_ai_hint: 'modern mansion'
  },
  {
    id: '53',
    title: 'Venice Beach Architectural',
    price: 4800000,
    address: '53 Abbot Kinney, Venice, USA',
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'House',
    description: 'A stunning architectural home just steps from Abbot Kinney Blvd. Features soaring ceilings and a rooftop deck with ocean views.',
    amenities: ['Rooftop Deck', 'Ocean Views', 'Walking distance to shops'],
    agentId: '2',
    data_ai_hint: 'modern beach house'
  },
  {
    id: '54',
    title: 'Downtown LA Arts District Loft',
    price: 1650000,
    address: '54 Arts District, Los Angeles, USA',
    bedrooms: 2,
    bathrooms: 2,
    area: 2200,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: false,
    type: 'Loft',
    description: 'A spacious loft in the vibrant Arts District. Features polished concrete floors and a communal rooftop pool.',
    amenities: ['Rooftop Pool', 'Polished Concrete Floors', 'Exposed Brick'],
    agentId: '3',
    data_ai_hint: 'artsy loft'
  },
  {
    id: '55',
    title: 'Malibu Beachfront Property',
    price: 9800000,
    address: '55 Pacific Coast Hwy, Malibu, USA',
    bedrooms: 5,
    bathrooms: 6,
    area: 4800,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'An incredible beachfront home on the sands of Malibu. Features a large deck, private beach access, and stunning sunset views.',
    amenities: ['Private Beach Access', 'Oceanfront Deck', 'Sunset Views'],
    agentId: '1',
    data_ai_hint: 'malibu beach house'
  },
  {
    id: '56',
    title: 'Hollywood Hills View Home',
    price: 6200000,
    address: '56 Stargazer Lane, Hollywood Hills, USA',
    bedrooms: 4,
    bathrooms: 5,
    area: 4100,
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/1200x800.png'],
    featured: true,
    type: 'House',
    description: 'A celebrity-style home in the Hollywood Hills with jetliner views of the city. Features a screening room and infinity pool.',
    amenities: ['City Views', 'Infinity Pool', 'Screening Room'],
    agentId: '2',
    data_ai_hint: 'hollywood hills house'
  }
];

const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'John & Jane Doe',
    company: 'Happy Homeowners',
    comment: 'RealEstate Explorer helped us find our dream home in just a week! The process was seamless and the agents were incredibly professional. We couldn\'t be happier.',
    image: 'https://placehold.co/100x100.png',
    data_ai_hint: "happy couple"
  },
  {
    id: '2',
    name: 'Peter Jones',
    company: 'First-Time Buyer',
    comment: 'As a first-time buyer, I was nervous about the process. The team at RealEstate Explorer guided me every step of the way. Highly recommended!',
    image: 'https://placehold.co/100x100.png',
    data_ai_hint: "smiling man"
  },
  {
    id: '3',
    name: 'Mary Smith',
    company: 'Property Investor',
    comment: 'I\'ve worked with many real estate companies, but RealEstate Explorer stands out. Their market knowledge and dedication are top-notch. They helped me find a great investment property.',
    image: 'https://placehold.co/100x100.png',
    data_ai_hint: "business woman"
  },
];

export const getProperties = async (): Promise<Property[]> => {
  return properties;
};

export const getFeaturedProperties = async (): Promise<Property[]> => {
  return properties.filter(p => p.featured);
};

export const getPropertyById = async (id: string): Promise<Property | undefined> => {
  return properties.find(p => p.id === id);
};

export const getAgents = async (): Promise<Agent[]> => {
  return agents;
};

export const getAgentById = async (id: string): Promise<Agent | undefined> => {
  return agents.find(a => a.id === id);
};

export const getTestimonials = async (): Promise<Testimonial[]> => {
  return testimonials;
};
